// <auto-generated />
namespace Resumes.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Tweak : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Tweak));
        
        string IMigrationMetadata.Id
        {
            get { return "201703251937128_Tweak"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
